
import HeaderTop from '@/components/HeaderTop';
import './global.css';
import type { Metadata } from 'next';
import HeaderMain from '@/components/HeaderMain';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer'

import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <HeaderTop />
        <HeaderMain />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
